ERROR_LOGIN_REQUIRED = 101
ERROR_INVALID_PASSWORD_USERNAME = 102

ERROR_INVALID_DATA_FORMAT = 103
ERROR_UNEXPECTED = 104


ERROR_EVENT_NON_EXIST = 105
ERROR_PARTICIPATE_NON_EXIST = 106


ERROR_DATE_INVALID = 107
ERROR_UNKNOWN_EVENT_TYPE = 108

ERROR_PAGE_EXCEEDED = 109
ERROR_EVENT_UNAVAILABLE = 110
