ERROR_LOGIN_REQUIRED = 101
ERROR_INVALID_PASSWORD_USERNAME = 102

ERROR_INVALID_DATA_FORMAT = 103
ERROR_UNEXPECTED = 104


ERROR_EVENT_NON_EXIST = 105
ERROR_DAILY_EVENT_LIMITS_EXCEEDED = 106

ERROR_DATE_INVALID = 107
ERROR_UNKNOWN_EVENT_TYPE = 108

ERROR_PAGE_EXCEEDED = 109
ERROR_EVENT_UNAVAILABLE = 110

ERROR_UNKNOWN_OP_TYPE = 111

ERROR_UNAUTHORIZED_OPERATION = 112

ERROR_SERVICE_UNAVAILABLE = 113
ERROR_USER_ALREADY_EXIST = 114
ERROR_UID_NON_EXIST = 115
ERROR_VERIFICATION_FAILED = 116

ERROR_INACTIVATE_ACCOUNT = 117

