# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtab',
            name='event_creator',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='third_party_connection',
            field=models.IntegerField(default=0),
        ),
    ]
