# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 04:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20180907_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtab',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 4, 16, 34, 474037)),
        ),
    ]
