# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 05:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_eventtab_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtab',
            name='event_date',
        ),
        migrations.AddField(
            model_name='eventtab',
            name='event_end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 5, 6, 29, 44700)),
        ),
        migrations.AddField(
            model_name='eventtab',
            name='event_start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 5, 6, 29, 44665)),
        ),
    ]
