# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20180907_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtab',
            name='is_open_ended',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventtab',
            name='event_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventtab',
            name='event_start_date',
            field=models.DateTimeField(),
        ),
    ]
