# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20180907_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liketab',
            name='pid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='participatetab',
            name='pid',
            field=models.IntegerField(db_index=True),
        ),
    ]
