# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20180907_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='liketab',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='participatetab',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
