# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20180907_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewHistoryTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.UUIDField(db_index=True)),
                ('pid', models.IntegerField(db_index=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'history_view_tab',
            },
        ),
    ]
