# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-08 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_viewhistorytab'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events_created_daily',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='viewhistorytab',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
