# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-08 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_auto_20180908_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='authy_id',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=24),
        ),
    ]
